### ISSUE TITLE
Rankings on superkingdom and spcies level

### ISSUE THREAD

**Issue by nlapier2** [CAMI-challenge/OPAL#28] opened 2019-05-15 01:28 UTC
It seems as though the rankings in the rankings table are computed using only the genus through phylum ranks, leaving out superkingdom and species. Is this the intended behavior? If so, is there any way to change it?

Thanks!

**Comment by fernandomeyer** [comment] 2019-05-15 09:48
This was initially the intended behavior because the performance of some tools dropped a lot below genus, but you're right in that other taxonomic ranks should be selectable as well. You can now use option --ranks with a comma-separated pair of taxonomic ranks - default is superkingdom,species, meaning that the ranking scores will be computed from superkingdom to species. Fixed in commit d93a4d4ec93b5d2aa4592cab3b67d49cc4bf22d9.

**Closed by fernandomeyer** 2019-05-15 09:48 UTC
